apiVersion: v1
kind: ReplicationController
metadata:
  name: myapp-rc
  labels:
    app: myapp
    type: frontend
spec:  # replication controller
  template:  # pod template to be used by the RC to create replicas (pod-definition.yaml)
    metadata:
      name: myapp-pod
      labels:
        app: myapp
        type: frontend
    spec:
      containers:
        - name: nginx-container
          image: nginx
  replicas: 3
# selector is supported but not required
# assumes same as the labels provided in the pod definition